[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "payload-sniper"
version = "1.3.0"
description = "Edge-cached code split, INP and Core Web Vitals script bloat-tracer"
readme = "README.md"
authors = [
  { name = "xcalibur73" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    # PolyForm Noncommercial 1.0.0
    "License :: Free For Educational Use",
    "License :: Free For Non-commercial Use",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Software Development :: Quality Assurance"
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "rich>=13.7.0",
    "websockets>=12.0"
]

[project.scripts]
payload-sniper = "payload_sniper.cli:main"

[project.urls]
"Homepage" = "https://github.com/xcalibur73/payload-sniper"
"Cloud Engine" = "https://webaudits.pro/tools/payload-sniper"
"Bug Tracker" = "https://github.com/xcalibur73/payload-sniper/issues"
